name: CI

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

  workflow_dispatch:

jobs:
  build_and_test:
    name: Test plugin on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-12 -DCMAKE_CXX_COMPILER=clang++-12"
          - os: windows-2019
            cmake_args: "-T ClangCl"
          - os: macos-latest
            cmake_args: "-DCMAKE_BUILD_TYPE=Release"
    
    steps:
    - name: Install Linux Deps
      if: runner.os == 'Linux'
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main"
        sudo apt update
        sudo apt install clang-12 -y
        sudo apt-get update
        sudo apt install libasound2-dev libcurl4-openssl-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev libjack-jackd2-dev

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure
      shell: bash
      run: cmake -Bbuild ${{ matrix.cmake_args }}

    - name: Build
      shell: bash
      run: cmake --build build --config Release --parallel 4 --target ChowMultiTool_Standalone ChowMultiTool_VST3 ChowMultiTool_CLAP

    - name: Build AU
      if: runner.os == 'MacOS'
      shell: bash
      run: cmake --build build --config Release --parallel 4 --target ChowMultiTool_AU

    - name: Build LV2
      if: runner.os == 'Linux'
      shell: bash
      run: cmake --build build --config Release --parallel 4 --target ChowMultiTool_LV2

    - name: Pluginval
      if: runner.os == 'Windows' # || runner.os == 'MacOS'
      run: bash scripts/pluginval.sh

#    - name: clap-validator
#      run: bash scripts/clap-validate.sh
